name: Feature Request or Engineering Bug Report
description: File a Feature report
title: "[FR or BR]: Customer | ARR | Priority | Description"
assignees:
  - "gauravdhy"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting this request!
  - type: input
    id: customer
    attributes:
      label: Customer
    validations:
      required: true
  - type: input
    id: arr
    attributes:
      label: ARR
    validations:
      required: true
  - type: input
    id: revenue-impact
    attributes:
      label: Revenue Impact (+ Net New / - Loss)
    validations:
      required: true
  - type: dropdown
    id: revenue-impact-probability
    attributes:
      label: Revenue Impact Probability
      options:
        - No Impact
        - Low
        - Medium
        - High
        - Certain
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Tell us more
      placeholder: Share more details with us. 
      value: "New ask from the customer!"
    validations:
      required: true
  - type: dropdown
    id: priority-level
    attributes:
      label: Priority Level
      options:
        - Critical
        - Standard
    validations:
      required: true
  - type: textarea
    id: action
    attributes:
      label: Desired Outcome?  
      description: What do you want the engineering/product to do?
      placeholder: Share more details with us. 
      value: "Customer requesting fix by ..."
    validations:
      required: true
  - type: checkboxes
    id: business-impact
    attributes:
      label: Customer Business Impact
      description: What is the importance of this issue from the customer's point of view
      options:
        - label: Deal/Upsell Blocker 
        - label: Renewal Blocker
        - label: Customer Sentiment Issue
        - label: Nice To Have
  - type: input 
    id: due-date
    attributes:
      label: Customer requested target timeline (if any)?
      value: None
  - type: checkboxes
    id: product-area
    attributes:
      label: Product Area
      description: What area does this request relate to?
      options:
        - label: SSH
        - label: K8
        - label: Database
        - label: Application
        - label: Desktop
        - label: Integrations
  - type: input
    id: other-customers
    attributes:
      label: Other Customers?
      value: None
  - type: input 
    id: linked-issues
    attributes:
      label: Linked Issues
      value: None
  - type: input 
    id: commitment
    attributes:
      label: Engineering Committed Timeframe/Release
      value: None

