name: Feature Request or Engineering Bug Report
description: File a Feature report
title: "[FR or BR]: Customer | ARR | Priority | Description"
assignees:
  - "gauravdhy"
body:
  - type: markdown
    attributes:
      value: |
        NEW FEATURE REQUEST OR BUG REPORT SUBMISSION FORM!
  - type: input
    id: customer
    attributes:
      label: Customer
    validations:
      required: true
  - type: input
    id: arr
    attributes:
      label: ARR
    validations:
      required: true
  - type: input
    id: revenue-impact
    attributes:
      label: Revenue Impact (+ Net New / - Loss)
    validations:
      required: true
  - type: dropdown
    id: revenue-impact-probability
    attributes:
      label: Revenue Impact Probability
      options:
        - No Impact
        - Low
        - Medium
        - High
        - Certain
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Tell us more
      placeholder: Share more details with us. 
      value: "New ask from the customer!"
    validations:
      required: true
  - type: checkboxes
    id: business-impact
    attributes:
      label: What is the potential impact of not addressing this request?
      description: Non Revenue Impact 
      options:
        - label: Unknown (It is a Support Request)
        - label: Customer Sentiment Issue
        - label: Nice To Have
  - type: textarea
    id: action
    attributes:
      label: Desired Outcome?  
      description: What do you want the engineering/product to do?
      placeholder: Share more details with us. 
      value: ___
    validations:
      required: true
  - type: input 
    id: due-date
    attributes:
      label: Customer requested target timeline (if any)?
      value: None
  - type: checkboxes
    id: product-area
    attributes:
      label: Product Area
      description: What area does this request relate to?
      options:
        - label: SSH
        - label: K8
        - label: Database
        - label: Application
        - label: Desktop
        - label: Integrations
  - type: input
    id: other-customers
    attributes:
      label: Other Customers?
      value: None
  - type: input 
    id: linked-issues
    attributes:
      label: Linked Issues (separate by ; )
      value: None
  - type: dropdown
    id: engineering-effort-estimate
    attributes:
      label: Effort Estimate
      options:
        - Estimate Unknown
        - X Large
        - Large
        - Medium
        - Small
        - Tiny
  - type: input 
    id: commitment
    attributes:
      label: Engineering Committed Timeframe/Release
      value: TBD
