name: Feature Request or Engineering Bug Report
description: File a Feature report
title: "[FR or BR]: Customer | ARR | Priority | Description"
assignees:
  - "gauravdhy"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting this request!
  - type: input
    id: customer
    attributes:
      label: Customer
    validations:
      required: true
  - type: input
    id: ARR
    attributes:
      label: ARR
    validations:
      required: true  
  - type: textarea
    id: Details
    attributes:
      label: Details
      description: Tell us more
      placeholder: Share more details with us. 
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: priority-level
    attributes:
      label: Priority Level
      options:
        - Critical
        - Standard
    validations:
      required: true
  - type: dropdown
    id: potential-top-ten-candidate
    attributes:
      label: Potential Top Ten Candidate?
      description: Is this a potential top ten candidate?
      options:
        - "No" 
        - "Yes" 
    validations:
      required: true
  - type: checkboxes
    id: business-impact
    attributes:
      label: Customer Business Impact
      description: What is the importance of this issue from the customer's point of view
      options:
        - label: Deal Blocker 
        - label: Renewal Blocker
        - label: Upsell Blocker
        - label: Customer Sentiment Issue
        - label: Nice To Have
  - type: checkboxes
    id: impact-topic
    attributes:
      label: Impact Topic
      description: What area does this request relate to?
      options:
        - label: SSH
        - label: K8
        - label: Database
        - label: Application
        - label: Desktop
        - label: Integrations
